<?xml version="1.0" encoding="utf-8"?><testsuite errors="0" failures="1" name="pytest" skips="0" tests="2" time="0.201"><testcase classname="test_main" file="test_main.py" line="11" name="test_get_temperature_by_lat_lng[-14.235004--51.92528-16]" time="0.003212451934814453"></testcase><testcase classname="test_main" file="test_main.py" line="22" name="test_get_temperature_with_invalid_lat_or_lng_type[None--51.92528-expected0]" time="0.002048015594482422"><failure message="AssertionError: assert 16 == {&apos;code&apos;: 400, &apos;error&apos;: &apos;Invalid data type. Please try again.&apos;}">E   AssertionError: assert 16 == {&apos;code&apos;: 400, &apos;error&apos;: &apos;Invalid data type. Please try again.&apos;}</failure></testcase></testsuite>